apiVersion: v1
kind: Service
metadata:
  name: thrifty-service
  namespace: thrifty
spec:
  selector:
    app: thrifty-frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007

